apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: account-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: account-service
    spec:
      containers:
      - image: zhangkanglong/demo:account-service
        name: account-service
        ports:
        - containerPort: 8080
        resources: {}

status: {}
